In [81]:
import numpy as np

In [54]:
np.random.seed (0)
A = np.random.randint (0,10,[5,5])
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [12]:
A.sum ()

27

In [17]:
A.sum (axis = 1)

array([ 8, 19])

In [19]:
A.cumsum ()

array([ 5,  5,  8, 11, 18, 27])

In [25]:
A.min (axis = 0)

array([3, 0, 3])

In [26]:
A.argmin (axis = 0)

array([1, 0, 0])

In [34]:
A.argsort ()

array([[1, 2, 0],
       [0, 1, 2]])

In [36]:
np.exp (A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

## Stat


In [38]:
A.mean ()

4.5

In [40]:
A.std () #ecart -type

2.9297326385411577

In [42]:
A.var () #variance

8.583333333333334

In [50]:
#coefficient de correlation
np.corrcoef (A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [51]:
np.corrcoef (A)[0,1]

-0.563621480190678

In [60]:
value,counts = np.unique (A,return_counts= True)
print (value,counts)

[0 1 2 3 4 5 6 7 8 9] [1 2 1 3 2 3 2 4 4 3]


In [62]:
value [counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

## Algebre lineare


In [68]:
A = np.ones ((2,3))
B = np.ones ((3,2))
print (A)
print()
print (B)

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [70]:
A.T #transposee d'une matrice

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
A.dot (B) #produit matricielle

array([[3., 3.],
       [3., 3.]])

In [74]:
B.dot (A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

## exercice

In [77]:
#normalisation des donnee
np.random.seed (0)
Data = np.random.randint (0,100,[10,5])
Data

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [96]:
# data - mean (data)/ecartype (Data)
norm = (Data - Data.mean (axis=0)) / Data.std (axis = 0)
norm 

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [93]:
print (Data.shape)
norm.shape

(10, 5)


(10, 5)