## Numpy broadcasting

In [9]:
import numpy as np
np.random.seed (0)
A = np.random.randint (0,10,[2,3])
B = np.ones((2,3))
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
A 

array([[5, 0, 3],
       [3, 7, 9]])

In [11]:
A + B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [14]:
A + 2

array([[ 7,  2,  5],
       [ 5,  9, 11]])