## Machine Learnia

In [13]:
import numpy as np
  

In [6]:
A = np.array ([1,2,3]) #creation d'un Ndarray
A

array([1, 2, 3])

In [9]:
A.shape # taille du tableau 

(3,)

In [10]:
B = np.zeros ((3,2)) #cree une tableau rempli de zeros
#np.ones cree une tableau rempli de un
# np.full ((size),number) cree une tableau rempli de number
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
C = np.random.randn (3,4)# initialise le tableau avec des valeur aleatoire
C

array([[-0.29619396,  0.31670415,  0.90171522, -1.11329338],
       [ 0.33598957,  0.00346408, -0.37585938, -1.09346172],
       [ 0.12604932, -0.2706075 , -0.84693914,  0.33148308]])

In [14]:
np.random.seed (10) #fixe le generateur aleatoire pour produire le meme resultat
D  = np.random.randn (3,2)
D

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556]])

In [54]:
z = np.ones((2,3))
y = np.zeros ((2,3))

In [18]:
np.linspace (0,10,20) #cree une tableau a une dimension 


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.arange (0,10,2)

array([0, 2, 4, 6, 8])

In [56]:
np.hstack ((z,y))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

## Manipulation

In [27]:
E = np.zeros ((3,2))
F = np.ones ((3,2))

In [31]:
G = np.hstack ((E,F)) # coller les deux tableau de facon horizontale
G

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [32]:
H = np.vstack ((E,F)) #coller les deux tableau de facon verticale
H

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
np.concatenate ((E,F), axis = 1)#coller les deux tableau de facon horizontale


array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [37]:
np.concatenate ((E,F), axis = 0)#coller les deux tableau de facon verticale


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
H = H.reshape ((3,4))
H

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
I = np.array ([1,2,3])
I = I.reshape ((I.shape[0],1))
I.shape 

(3, 1)

In [48]:
I = I.squeeze ()
I.shape

(3,)

In [51]:
H.ravel ().shape

(12,)

In [3]:
def initialisation (m,n):
    Array1 = np.zeros ((m,n))
    Array2 = np.ones ((m,1))
    Array1.reshape ((m*n,1))
    Array3 = np.concatenate ((Array1,Array2),axis = 1);
    return Array3.reshape ((m,(n+1)))

initialisation (10,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
def initi (m,n):
    X = np.random.randn (m,n)
    X = np.concatenate ((X,np.ones(( X.shape [0],1))), axis = 1)
    return X

initi (4,2)

array([[-0.91634866, -0.0374988 ,  1.        ],
       [ 0.45610517,  0.1923219 ,  1.        ],
       [-0.36197356,  1.45690561,  1.        ],
       [ 1.92779989, -0.72307028,  1.        ]])