    ANALYSE DE DONNEE AVEC PANDAS & NUMPY

In [1]:
import numpy as np


In [2]:
np.array ([1,2,3]) #cree une array (ndarray)

array([1, 2, 3])

In [3]:
np.arange (10)  #cree une array de 0 a 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
 # cree une array de 10 element puis le transforme 
 #en matrice de 5 ligne et 2 colonnes
np.arange (10).reshape (5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
#cree une matrice rempli de zero
np.zeros ((3,3))

#cree une matrice rempli de un : np.ones ((i,j))
#cree une matrice d'identite : np.eye ((i,j))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#cree une array de dimension 1 aleatoire de dimension 
# 1 aleatoire de n element

np.random.rand (10)

array([0.56225865, 0.31234755, 0.81158479, 0.61327104, 0.06042137,
       0.24255328, 0.0943483 , 0.81688906, 0.55024417, 0.86324986])

In [7]:
#cree une array de dimension 1 aleatoire de dimension 
# i,j random
np.random.random (size = (3,2))

array([[0.13812512, 0.74041693],
       [0.78945118, 0.86831769],
       [0.55794094, 0.00736838]])

In [8]:
#indexing

myarray = np.random.rand (5)
print (myarray)
print (type (myarray))

print ()

myarray_multidim = np.random.rand (16).reshape (4,4)
print (myarray_multidim )
print (type (myarray_multidim))

print ()

print (myarray_multidim [2,1])
print (myarray_multidim [1:3,1]) #affiche le 2er et 3e ligne de la 2e colone
print (myarray_multidim [2,0:2]) #affiche le 1er et 2e colonne de la 3e ligne
print (myarray_multidim [:,0]) #affiche la 1er colonne
print (myarray_multidim [0,:]) #affiche la 1er ligne


[0.8409123  0.33280775 0.2646928  0.67381935 0.684922  ]
<class 'numpy.ndarray'>

[[0.50523411 0.45963496 0.56206799 0.8087256 ]
 [0.26963018 0.23704066 0.78873011 0.67931698]
 [0.59579991 0.51440996 0.73519583 0.73881041]
 [0.63524497 0.50340718 0.33326407 0.05355829]]
<class 'numpy.ndarray'>

0.5144099566269646
[0.23704066 0.51440996]
[0.59579991 0.51440996]
[0.50523411 0.26963018 0.59579991 0.63524497]
[0.50523411 0.45963496 0.56206799 0.8087256 ]


In [9]:
#np.shape donee la dimension i,j du matrice
#np.ndim  donnee la dimension 1d,2d,3d,...
#np.size  donnee la taille 
print(myarray_multidim.shape) 
print(myarray_multidim.ndim) 
print(myarray_multidim.size) 

(4, 4)
2
16


In [10]:
#np.cos,np.log,np.exp,np.sqrt,...
#applique une calcule mathematique sur 
#toute la matrice
myarray = np.arange(10).reshape (5,2) 
print (myarray)
print (np.cos(myarray))
print (np.exp (myarray))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]]
[[1.00000000e+00 2.71828183e+00]
 [7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03]]


In [11]:
#fontions np.sum,np.min,np.max,np.mean
print(myarray)
print (myarray.min())
print (myarray.max())
print (myarray.mean())
print (myarray.sum())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
0
9
4.5
45


    calcule matricielle

In [12]:
#produit element par element
A = np.arange(16).reshape (4,4)
print (A)
B = np.random.rand(16).reshape (4,4)
print (B)
print ()
print (A*B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0.55830888 0.50340676 0.30342036 0.85209354]
 [0.83198231 0.22238758 0.04962361 0.51951992]
 [0.73306963 0.25274948 0.93724865 0.07700374]
 [0.22753869 0.64387574 0.069211   0.51611344]]

[[0.         0.50340676 0.60684073 2.55628062]
 [3.32792925 1.11193788 0.29774164 3.63663942]
 [5.86455702 2.27474532 9.37248647 0.84704117]
 [2.73046426 8.37038463 0.96895403 7.74170155]]


In [13]:
#produit matricil ou array1.dot (array2)
print (A@B)
print ()
print (A.dot (B))

[[ 2.98073763  2.65951376  2.13175391  2.22186771]
 [12.38433566  9.14919198  7.56976838 10.08079026]
 [21.78793368 15.6388702  13.00778286 17.9397128 ]
 [31.1915317  22.12854842 18.44579733 25.79863535]]

[[ 2.98073763  2.65951376  2.13175391  2.22186771]
 [12.38433566  9.14919198  7.56976838 10.08079026]
 [21.78793368 15.6388702  13.00778286 17.9397128 ]
 [31.1915317  22.12854842 18.44579733 25.79863535]]


In [14]:
#transposee d'une matrice
C = np.arange (12).reshape (4,3)
print (C)
print ()
C = C.T
print (C)
print ()
print (C.transpose ())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
#matrice inversible
#np.linalg.inv (matrice) matrice carre
np.linalg.inv (np.random.rand (16).reshape(4,4))

array([[  2.40605505,  -1.37919918,   7.26071828,  -4.72383356],
       [ -0.89246372,   0.54412504, -11.02320311,   7.67607447],
       [ -3.60066165,   4.645706  , -20.60132532,  12.05788862],
       [  0.3362168 ,  -0.70918319,  12.57972947,  -6.90130577]])

        Pandas

In [16]:
import pandas as pd

pd.Series (np.array([1,2,3]))


0    1
1    2
2    3
dtype: int64

In [17]:
pd.DataFrame ({"col1":[1,2,3],
              "col2":[5,4,3]})

col1  col2
0     1     5
1     2     4
2     3     3

In [18]:

pd.DataFrame ({'P':['Profil','Papa'],
            'ans': ['Eau','clavier']})

P      ans
0  Profil      Eau
1    Papa  clavier

In [19]:
df_covid = pd.read_csv ("04-19-2020.csv")
df_covid.head (5)

FIPS     Admin2  Province_State Country_Region          Last_Update  \
0  45001.0  Abbeville  South Carolina             US  2020-04-19 23:41:01   
1  22001.0     Acadia       Louisiana             US  2020-04-19 23:41:01   
2  51001.0   Accomack        Virginia             US  2020-04-19 23:41:01   
3  16001.0        Ada           Idaho             US  2020-04-19 23:41:01   
4  19001.0      Adair            Iowa             US  2020-04-19 23:41:01   

         Lat       Long_  Confirmed  Deaths  Recovered  Active  \
0  34.223334  -82.461707         17       0          0      17   
1  30.295065  -92.414197        110       7          0     103   
2  37.767072  -75.632346         42       0          0      42   
3  43.452658 -116.241552        598      10          0     588   
4  41.330756  -94.471059          1       0          0       1   

                    Combined_Key  
0  Abbeville, South Carolina, US  
1          Acadia, Louisiana, US  
2         Accomack, Virginia, US  
3                 Ada, Idaho, US  
4                Adair, Iowa, US

In [20]:
#enregistre en memoire 
#def_covid = df_covid.set_index ('Country_Region').head ()
df_covid.set_index ('Country_Region', inplace=True)
df_covid.head (2)

FIPS     Admin2  Province_State          Last_Update  \
Country_Region                                                            
US              45001.0  Abbeville  South Carolina  2020-04-19 23:41:01   
US              22001.0     Acadia       Louisiana  2020-04-19 23:41:01   

                      Lat      Long_  Confirmed  Deaths  Recovered  Active  \
Country_Region                                                               
US              34.223334 -82.461707         17       0          0      17   
US              30.295065 -92.414197        110       7          0     103   

                                 Combined_Key  
Country_Region                                 
US              Abbeville, South Carolina, US  
US                      Acadia, Louisiana, US

In [21]:
df_covid = df_covid.reset_index ()
df_covid.head (3)

Country_Region     FIPS     Admin2  Province_State          Last_Update  \
0             US  45001.0  Abbeville  South Carolina  2020-04-19 23:41:01   
1             US  22001.0     Acadia       Louisiana  2020-04-19 23:41:01   
2             US  51001.0   Accomack        Virginia  2020-04-19 23:41:01   

         Lat      Long_  Confirmed  Deaths  Recovered  Active  \
0  34.223334 -82.461707         17       0          0      17   
1  30.295065 -92.414197        110       7          0     103   
2  37.767072 -75.632346         42       0          0      42   

                    Combined_Key  
0  Abbeville, South Carolina, US  
1          Acadia, Louisiana, US  
2         Accomack, Virginia, US

In [22]:
#renomer des colonnes et index df.rename  (columns = (old_name:new_name),index = (old_name:new_name))
df_covid.rename (columns={'Admin2':'Admin'} ,inplace=True)
df_covid.head(3)


Country_Region     FIPS      Admin  Province_State          Last_Update  \
0             US  45001.0  Abbeville  South Carolina  2020-04-19 23:41:01   
1             US  22001.0     Acadia       Louisiana  2020-04-19 23:41:01   
2             US  51001.0   Accomack        Virginia  2020-04-19 23:41:01   

         Lat      Long_  Confirmed  Deaths  Recovered  Active  \
0  34.223334 -82.461707         17       0          0      17   
1  30.295065 -92.414197        110       7          0     103   
2  37.767072 -75.632346         42       0          0      42   

                    Combined_Key  
0  Abbeville, South Carolina, US  
1          Acadia, Louisiana, US  
2         Accomack, Virginia, US

In [23]:
#acceder aux donnees 
df_covid ['Country_Region'] == 'US'

0        True
1        True
2        True
3        True
4        True
        ...  
3105    False
3106    False
3107    False
3108    False
3109    False
Name: Country_Region, Length: 3110, dtype: bool

In [24]:
df_covid.shape

(3110, 12)

In [25]:
df_covid[df_covid ['Country_Region'] == 'US'].shape


(2810, 12)

In [26]:
((df_covid[df_covid ['Country_Region'] == 'US'].shape[0])/df_covid.shape[0])*100

90.35369774919614

In [27]:
temperature = pd.read_csv ("~/Bureau/lm35xdht11xdht22.csv")
temperature

LM35  DHT22_T  DHT11_T  DHT22_H  DHT11_H
0     22.37     24.8     24.0     74.8     71.0
1     22.37     24.8     24.0     74.8     71.0
2     22.37     24.8     24.0     74.7     71.0
3     21.40     24.8     24.0     74.7     71.0
4     21.89     24.8     24.0     74.8     71.0
...     ...      ...      ...      ...      ...
1157  21.89     24.7     24.0     74.5     71.0
1158  22.86     24.7     24.0     74.5     71.0
1159  21.89     24.7     24.0     74.5     71.0
1160  22.86     24.7     24.0     74.4     71.0
1161  22.86     24.7     24.0     74.4     71.0

[1162 rows x 5 columns]