    ANALYSE DE DONNEE AVEC PANDAS & NUMPY

In [47]:
import numpy as np


In [48]:
np.array ([1,2,3]) #cree une array (ndarray)

array([1, 2, 3])

In [49]:
np.arange (10)  #cree une array de 0 a 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
 # cree une array de 10 element puis le transforme 
 #en matrice de 5 ligne et 2 colonnes
np.arange (10).reshape (5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
#cree une matrice rempli de zero
np.zeros ((3,3))

#cree une matrice rempli de un : np.ones ((i,j))
#cree une matrice d'identite : np.eye ((i,j))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
#cree une array de dimension 1 aleatoire de dimension 
# 1 aleatoire de n element

np.random.rand (10)

array([0.14423403, 0.01683302, 0.99190576, 0.1261717 , 0.09963478,
       0.33989315, 0.99202036, 0.83412568, 0.08806337, 0.65810135])

In [53]:
#cree une array de dimension 1 aleatoire de dimension 
# i,j random
np.random.random (size = (3,2))

array([[0.82911758, 0.51335193],
       [0.08415334, 0.53303182],
       [0.0234848 , 0.57006003]])

In [54]:
#indexing

myarray = np.random.rand (5)
print (myarray)
print (type (myarray))

print ()

myarray_multidim = np.random.rand (16).reshape (4,4)
print (myarray_multidim )
print (type (myarray_multidim))

print ()

print (myarray_multidim [2,1])
print (myarray_multidim [1:3,1]) #affiche le 2er et 3e ligne de la 2e colone
print (myarray_multidim [2,0:2]) #affiche le 1er et 2e colonne de la 3e ligne
print (myarray_multidim [:,0]) #affiche la 1er colonne
print (myarray_multidim [0,:]) #affiche la 1er ligne


[0.60920412 0.13373919 0.88657373 0.78696145 0.66707374]
<class 'numpy.ndarray'>

[[0.94189578 0.79364797 0.05529904 0.35524397]
 [0.30801862 0.11469701 0.71283593 0.74720897]
 [0.42446287 0.58531922 0.54787527 0.35947065]
 [0.52096756 0.61901775 0.54772784 0.43878633]]
<class 'numpy.ndarray'>

0.5853192200295975
[0.11469701 0.58531922]
[0.42446287 0.58531922]
[0.94189578 0.30801862 0.42446287 0.52096756]
[0.94189578 0.79364797 0.05529904 0.35524397]


In [55]:
#np.shape donee la dimension i,j du matrice
#np.ndim  donnee la dimension 1d,2d,3d,...
#np.size  donnee la taille 
print(myarray_multidim.shape) 
print(myarray_multidim.ndim) 
print(myarray_multidim.size) 

(4, 4)
2
16


In [ ]:
#np.cos,np.log,np.exp,np.sqrt,...
np.arrange(10).reshape (5,2)