    ANALYSE DE DONNEE AVEC PANDAS & NUMPY

In [22]:
import numpy as np


In [23]:
np.array ([1,2,3]) #cree une array (ndarray)

array([1, 2, 3])

In [24]:
np.arange (10)  #cree une array de 0 a 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
 # cree une array de 10 element puis le transforme 
 #en matrice de 5 ligne et 2 colonnes
np.arange (10).reshape (5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
#cree une matrice rempli de zero
np.zeros ((3,3))

#cree une matrice rempli de un : np.ones ((i,j))
#cree une matrice d'identite : np.eye ((i,j))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
#cree une array de dimension 1 aleatoire de dimension 
# 1 aleatoire de n element

np.random.rand (10)

array([0.63539294, 0.13429853, 0.20491097, 0.28076808, 0.23789705,
       0.20318224, 0.89028765, 0.59511056, 0.92254549, 0.40372385])

In [28]:
#cree une array de dimension 1 aleatoire de dimension 
# i,j random
np.random.random (size = (3,2))

array([[0.20207839, 0.46343251],
       [0.94407089, 0.00881585],
       [0.43806825, 0.78737305]])

In [29]:
#indexing

myarray = np.random.rand (5)
print (myarray)
print (type (myarray))

print ()

myarray_multidim = np.random.rand (16).reshape (4,4)
print (myarray_multidim )
print (type (myarray_multidim))

print ()

print (myarray_multidim [2,1])
print (myarray_multidim [1:3,1]) #affiche le 2er et 3e ligne de la 2e colone
print (myarray_multidim [2,0:2]) #affiche le 1er et 2e colonne de la 3e ligne
print (myarray_multidim [:,0]) #affiche la 1er colonne
print (myarray_multidim [0,:]) #affiche la 1er ligne


[0.72066161 0.15833179 0.52685362 0.35650892 0.50167413]
<class 'numpy.ndarray'>

[[0.06628388 0.61411021 0.54234941 0.14207896]
 [0.94281352 0.5115556  0.53257687 0.65165985]
 [0.85709831 0.06482755 0.52292464 0.63661129]
 [0.07589293 0.46288343 0.92757565 0.84212178]]
<class 'numpy.ndarray'>

0.06482754709684924
[0.5115556  0.06482755]
[0.85709831 0.06482755]
[0.06628388 0.94281352 0.85709831 0.07589293]
[0.06628388 0.61411021 0.54234941 0.14207896]


In [30]:
#np.shape donee la dimension i,j du matrice
#np.ndim  donnee la dimension 1d,2d,3d,...
#np.size  donnee la taille 
print(myarray_multidim.shape) 
print(myarray_multidim.ndim) 
print(myarray_multidim.size) 

(4, 4)
2
16


In [31]:
#np.cos,np.log,np.exp,np.sqrt,...
#applique une calcule mathematique sur 
#toute la matrice
myarray = np.arange(10).reshape (5,2) 
print (myarray)
print (np.cos(myarray))
print (np.exp (myarray))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]]
[[1.00000000e+00 2.71828183e+00]
 [7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03]]


In [32]:
#fontions np.sum,np.min,np.max,np.mean
print(myarray)
print (myarray.min())
print (myarray.max())
print (myarray.mean())
print (myarray.sum())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
0
9
4.5
45


    calcule matricielle

In [35]:
#produit element par element
A = np.arange(16).reshape (4,4)
print (A)
B = np.random.rand(16).reshape (4,4)
print (B)
print ()
print (A*B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0.85438183 0.47466019 0.78244062 0.13175945]
 [0.41360638 0.05638469 0.29264284 0.46344646]
 [0.6270106  0.38422797 0.72429935 0.60293034]
 [0.37083984 0.38083092 0.09945936 0.77744217]]

[[ 0.          0.47466019  1.56488124  0.39527834]
 [ 1.65442551  0.28192343  1.75585704  3.24412522]
 [ 5.0160848   3.45805174  7.24299345  6.63223378]
 [ 4.45007813  4.95080197  1.392431   11.66163262]]


In [36]:
#produit matricil ou array1.dot (array2)
print (A@B)
print ()
print (A.dot (B))

[[ 2.78014711  1.96733339  2.0396196   4.00163367]
 [11.84350172  7.15174846  9.63498826 11.90394737]
 [20.90685633 12.33616354 17.23035692 19.80626106]
 [29.97021093 17.52057861 24.82572558 27.70857476]]

[[ 2.78014711  1.96733339  2.0396196   4.00163367]
 [11.84350172  7.15174846  9.63498826 11.90394737]
 [20.90685633 12.33616354 17.23035692 19.80626106]
 [29.97021093 17.52057861 24.82572558 27.70857476]]


In [38]:
#transposee d'une matrice
C = np.arange (12).reshape (4,3)
print (C)
print ()
C = C.T
print (C)
print ()
print (C.transpose ())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
#matrice inversible
#np.linalg.inv (matrice) matrice carre
np.linalg.inv (np.random.rand (16).reshape(4,4))

array([[ 0.54227128,  0.16563888,  0.9879427 , -0.5069242 ],
       [ 1.86865615,  0.97780624, -1.05042892, -0.47966072],
       [-1.52725766,  1.42006754, -1.46530707,  0.68874729],
       [-0.4910029 , -2.26692015,  2.03889524,  0.98542983]])

        Pandas

In [42]:
import pandas as pd

pd.Series (np.array([1,2,3]))


0    1
1    2
2    3
dtype: int64

In [46]:
pd.DataFrame ({"col1":[1,2,3],
              "col2":[5,4,3]})

col1  col2
0     1     5
1     2     4
2     3     3

In [50]:

pd.DataFrame ({'P':['Profil','Papa'],
            'ans': ['Eau','clavier']})

P      ans
0  Profil      Eau
1    Papa  clavier