    ANALYSE DE DONNEE AVEC PANDAS & NUMPY

In [1]:
import numpy as np


In [2]:
np.array ([1,2,3]) #cree une array (ndarray)

array([1, 2, 3])

In [3]:
np.arange (10)  #cree une array de 0 a 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
 # cree une array de 10 element puis le transforme 
 #en matrice de 5 ligne et 2 colonnes
np.arange (10).reshape (5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
#cree une matrice rempli de zero
np.zeros ((3,3))

#cree une matrice rempli de un : np.ones ((i,j))
#cree une matrice d'identite : np.eye ((i,j))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#cree une array de dimension 1 aleatoire de dimension 
# 1 aleatoire de n element

np.random.rand (10)

array([0.32019177, 0.20585265, 0.01908171, 0.15632269, 0.76514311,
       0.05544107, 0.98457264, 0.89616738, 0.81526879, 0.95608423])

In [7]:
#cree une array de dimension 1 aleatoire de dimension 
# i,j random
np.random.random (size = (3,2))

array([[0.52692356, 0.40491518],
       [0.65042421, 0.25797212],
       [0.33670408, 0.64959203]])

In [8]:
#indexing

myarray = np.random.rand (5)
print (myarray)
print (type (myarray))

print ()

myarray_multidim = np.random.rand (16).reshape (4,4)
print (myarray_multidim )
print (type (myarray_multidim))

print ()

print (myarray_multidim [2,1])
print (myarray_multidim [1:3,1]) #affiche le 2er et 3e ligne de la 2e colone
print (myarray_multidim [2,0:2]) #affiche le 1er et 2e colonne de la 3e ligne
print (myarray_multidim [:,0]) #affiche la 1er colonne
print (myarray_multidim [0,:]) #affiche la 1er ligne


[0.45771364 0.47938385 0.59933477 0.69644793 0.86445507]
<class 'numpy.ndarray'>

[[0.02254176 0.98920912 0.63556656 0.29264518]
 [0.83016714 0.10794577 0.3246906  0.7132279 ]
 [0.1125718  0.83901799 0.17496118 0.74962083]
 [0.93102602 0.12206115 0.98817535 0.40185754]]
<class 'numpy.ndarray'>

0.8390179893226873
[0.10794577 0.83901799]
[0.1125718  0.83901799]
[0.02254176 0.83016714 0.1125718  0.93102602]
[0.02254176 0.98920912 0.63556656 0.29264518]


In [9]:
#np.shape donee la dimension i,j du matrice
#np.ndim  donnee la dimension 1d,2d,3d,...
#np.size  donnee la taille 
print(myarray_multidim.shape) 
print(myarray_multidim.ndim) 
print(myarray_multidim.size) 

(4, 4)
2
16


In [12]:
#np.cos,np.log,np.exp,np.sqrt,...
#applique une calcule mathematique sur 
#toute la matrice
myarray = np.arange(10).reshape (5,2) 
print (myarray)
print (np.cos(myarray))
print (np.exp (myarray))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]]
[[1.00000000e+00 2.71828183e+00]
 [7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03]]
